# Generated by Django 4.0 on 2023-11-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_name',
            field=models.CharField(choices=[('PB1', 'publication 1'), ('PB2', 'publication 2'), ('PB3', 'publication 3')], max_length=3, null=True),
        ),
    ]
